#!/bin/sh
wget    -P amicorpus/ES2005a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2005a/audio/ES2005a.Mix-Headset.wav
wget    -P amicorpus/ES2005b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2005b/audio/ES2005b.Mix-Headset.wav
wget    -P amicorpus/ES2005c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2005c/audio/ES2005c.Mix-Headset.wav
wget    -P amicorpus/ES2005d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2005d/audio/ES2005d.Mix-Headset.wav
wget    -P amicorpus/ES2006a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2006a/audio/ES2006a.Mix-Headset.wav
wget    -P amicorpus/ES2006b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2006b/audio/ES2006b.Mix-Headset.wav
wget    -P amicorpus/ES2006c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2006c/audio/ES2006c.Mix-Headset.wav
wget    -P amicorpus/ES2006d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2006d/audio/ES2006d.Mix-Headset.wav
wget    -P amicorpus/ES2007a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2007a/audio/ES2007a.Mix-Headset.wav
wget    -P amicorpus/ES2007b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2007b/audio/ES2007b.Mix-Headset.wav
wget    -P amicorpus/ES2007c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2007c/audio/ES2007c.Mix-Headset.wav
wget    -P amicorpus/ES2007d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2007d/audio/ES2007d.Mix-Headset.wav
wget    -P amicorpus/ES2008a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2008a/audio/ES2008a.Mix-Headset.wav
wget    -P amicorpus/ES2008b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2008b/audio/ES2008b.Mix-Headset.wav
wget    -P amicorpus/ES2008c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2008c/audio/ES2008c.Mix-Headset.wav
wget    -P amicorpus/ES2008d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2008d/audio/ES2008d.Mix-Headset.wav
wget    -P amicorpus/ES2009a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2009a/audio/ES2009a.Mix-Headset.wav
wget    -P amicorpus/ES2009b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2009b/audio/ES2009b.Mix-Headset.wav
wget    -P amicorpus/ES2009c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2009c/audio/ES2009c.Mix-Headset.wav
wget    -P amicorpus/ES2009d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2009d/audio/ES2009d.Mix-Headset.wav
wget    -P amicorpus/ES2010a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2010a/audio/ES2010a.Mix-Headset.wav
wget    -P amicorpus/ES2010b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2010b/audio/ES2010b.Mix-Headset.wav
wget    -P amicorpus/ES2010c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2010c/audio/ES2010c.Mix-Headset.wav
wget    -P amicorpus/ES2010d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2010d/audio/ES2010d.Mix-Headset.wav
wget    -P amicorpus/IS1000a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1000a/audio/IS1000a.Mix-Headset.wav
wget    -P amicorpus/IS1000b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1000b/audio/IS1000b.Mix-Headset.wav
wget    -P amicorpus/IS1000c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1000c/audio/IS1000c.Mix-Headset.wav
wget    -P amicorpus/IS1000d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1000d/audio/IS1000d.Mix-Headset.wav
wget    -P amicorpus/IS1001a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1001a/audio/IS1001a.Mix-Headset.wav
wget    -P amicorpus/IS1001b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1001b/audio/IS1001b.Mix-Headset.wav
wget    -P amicorpus/IS1001c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1001c/audio/IS1001c.Mix-Headset.wav
wget    -P amicorpus/IS1001d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1001d/audio/IS1001d.Mix-Headset.wav
wget    -P amicorpus/IS1002b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1002b/audio/IS1002b.Mix-Headset.wav
wget    -P amicorpus/IS1002c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1002c/audio/IS1002c.Mix-Headset.wav
wget    -P amicorpus/IS1002d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1002d/audio/IS1002d.Mix-Headset.wav
wget    -P amicorpus/IS1003a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1003a/audio/IS1003a.Mix-Headset.wav
wget    -P amicorpus/IS1003b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1003b/audio/IS1003b.Mix-Headset.wav
wget    -P amicorpus/IS1003c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1003c/audio/IS1003c.Mix-Headset.wav
wget    -P amicorpus/IS1003d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1003d/audio/IS1003d.Mix-Headset.wav
wget    -P amicorpus/IS1004a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1004a/audio/IS1004a.Mix-Headset.wav
wget    -P amicorpus/IS1004b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1004b/audio/IS1004b.Mix-Headset.wav
wget    -P amicorpus/IS1004c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1004c/audio/IS1004c.Mix-Headset.wav
wget    -P amicorpus/IS1004d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1004d/audio/IS1004d.Mix-Headset.wav
wget    -P amicorpus/IS1005a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1005a/audio/IS1005a.Mix-Headset.wav
wget    -P amicorpus/IS1005b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1005b/audio/IS1005b.Mix-Headset.wav
wget    -P amicorpus/IS1005c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1005c/audio/IS1005c.Mix-Headset.wav
wget    -P amicorpus/IS1006a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1006a/audio/IS1006a.Mix-Headset.wav
wget    -P amicorpus/IS1006b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1006b/audio/IS1006b.Mix-Headset.wav
wget    -P amicorpus/IS1006c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1006c/audio/IS1006c.Mix-Headset.wav
wget    -P amicorpus/IS1006d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1006d/audio/IS1006d.Mix-Headset.wav
wget    -P amicorpus/IS1007a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1007a/audio/IS1007a.Mix-Headset.wav
wget    -P amicorpus/IS1007b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1007b/audio/IS1007b.Mix-Headset.wav
wget    -P amicorpus/IS1007c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1007c/audio/IS1007c.Mix-Headset.wav
wget    -P amicorpus/IS1007d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1007d/audio/IS1007d.Mix-Headset.wav
wget    -P amicorpus/TS3005a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3005a/audio/TS3005a.Mix-Headset.wav
wget    -P amicorpus/TS3005b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3005b/audio/TS3005b.Mix-Headset.wav
wget    -P amicorpus/TS3005c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3005c/audio/TS3005c.Mix-Headset.wav
wget    -P amicorpus/TS3005d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3005d/audio/TS3005d.Mix-Headset.wav
wget    -P amicorpus/TS3006a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3006a/audio/TS3006a.Mix-Headset.wav
wget    -P amicorpus/TS3006b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3006b/audio/TS3006b.Mix-Headset.wav
wget    -P amicorpus/TS3006c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3006c/audio/TS3006c.Mix-Headset.wav
wget    -P amicorpus/TS3006d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3006d/audio/TS3006d.Mix-Headset.wav
wget    -P amicorpus/TS3007a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3007a/audio/TS3007a.Mix-Headset.wav
wget    -P amicorpus/TS3007b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3007b/audio/TS3007b.Mix-Headset.wav
wget    -P amicorpus/TS3007c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3007c/audio/TS3007c.Mix-Headset.wav
wget    -P amicorpus/TS3007d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3007d/audio/TS3007d.Mix-Headset.wav
wget    -P amicorpus/TS3008a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3008a/audio/TS3008a.Mix-Headset.wav
wget    -P amicorpus/TS3008b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3008b/audio/TS3008b.Mix-Headset.wav
wget    -P amicorpus/TS3008c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3008c/audio/TS3008c.Mix-Headset.wav
wget    -P amicorpus/TS3008d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3008d/audio/TS3008d.Mix-Headset.wav
wget    -P amicorpus/TS3009a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3009a/audio/TS3009a.Mix-Headset.wav
wget    -P amicorpus/TS3009b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3009b/audio/TS3009b.Mix-Headset.wav
wget    -P amicorpus/TS3009c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3009c/audio/TS3009c.Mix-Headset.wav
wget    -P amicorpus/TS3009d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3009d/audio/TS3009d.Mix-Headset.wav
wget    -P amicorpus/TS3010a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3010a/audio/TS3010a.Mix-Headset.wav
wget    -P amicorpus/TS3010b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3010b/audio/TS3010b.Mix-Headset.wav
wget    -P amicorpus/TS3010c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3010c/audio/TS3010c.Mix-Headset.wav
wget    -P amicorpus/TS3010d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3010d/audio/TS3010d.Mix-Headset.wav
wget    -P amicorpus/TS3011a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3011a/audio/TS3011a.Mix-Headset.wav
wget    -P amicorpus/TS3011b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3011b/audio/TS3011b.Mix-Headset.wav
wget    -P amicorpus/TS3011c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3011c/audio/TS3011c.Mix-Headset.wav
wget    -P amicorpus/TS3011d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3011d/audio/TS3011d.Mix-Headset.wav
wget    -P amicorpus/TS3012a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3012a/audio/TS3012a.Mix-Headset.wav
wget    -P amicorpus/TS3012b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3012b/audio/TS3012b.Mix-Headset.wav
wget    -P amicorpus/TS3012c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3012c/audio/TS3012c.Mix-Headset.wav
wget    -P amicorpus/TS3012d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3012d/audio/TS3012d.Mix-Headset.wav
wget    -P amicorpus/EN2001a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001a/audio/EN2001a.Mix-Headset.wav
wget    -P amicorpus/EN2001b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001b/audio/EN2001b.Mix-Headset.wav
wget    -P amicorpus/EN2001d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001d/audio/EN2001d.Mix-Headset.wav
wget    -P amicorpus/IN1001/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1001/audio/IN1001.Mix-Headset.wav
wget    -P amicorpus/IN1002/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1002/audio/IN1002.Mix-Headset.wav
wget https://groups.inf.ed.ac.uk/ami/download/temp/amiBuild-9476-Sat-May-13-2023.manifest.txt
wget https://groups.inf.ed.ac.uk/ami/download/temp/../CCBY4.0.txt
